---
- name: Install and configure softflowd
  hosts: all
  become: yes
  
  tasks:
    - name: Install softflowd
      ansible.builtin.package:
        name: softflowd
        state: present

    - name: Create systemd service file for softflowd
      ansible.builtin.template:
        src: templates/softflowd.service.j2
        dest: /etc/systemd/system/softflowd.service
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable softflowd service
      ansible.builtin.systemd:
        name: softflowd
        enabled: yes

    - name: Start softflowd service
      ansible.builtin.systemd:
        name: softflowd
        state: started
